### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by ogechionuoha** [vascofazza/indoor-outdoor-image-classifier#4]
Following the Readme and testing out the classifier returns the following error.

> original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'

Traceback is:

> Traceback (most recent call last):
>   File "./src/predict.py", line 35, in <module>
>     predict(args)
>   File "./src/predict.py", line 15, in predict
>     model.load_weights()
>   File "/indoor-outdoor-image-classifier/src/model/CNN_model.py", line 33, in load_weights
>     self.model.load_weights(last_checkpoint)
>   File "/Users/temp/opt/anaconda3/envs/base/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/Users/temp/opt/anaconda3/envs/base/lib/python3.7/site-packages/keras/engine/network.py", line 1230, in load_weights
>     f, self.layers, reshape=reshape)
>   File "/Users/temp/opt/anaconda3/envs/base/lib/python3.7/site-packages/keras/engine/saving.py", line 1183, in load_weights_from_hdf5_group
> original_keras_version = f.attrs['keras_version'].decode('utf8')
> AttributeError: 'str' object has no attribute 'decode'

The exact libraries in requirements.txt have been installed.

**Comment by ogechionuoha** [comment]
[Here's what worked for me](https://stackoverflow.com/a/64635871)

I simply downgraded h5py to 2.10.0 and it worked. 

Thanks.
